name: uniname
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1
  get: ^4.6.5
  device_preview: ^1.1.0
  cached_network_image: ^3.2.3
#  connectivity_plus: ^4.0.1
  flutter_svg: ^2.0.6
  fluttertoast: ^8.2.2
  page_transition: ^2.0.9
  carousel_slider: ^4.2.1
  pinput: ^2.2.31
  url_launcher: ^6.1.11
  flutter_easyloading: ^3.0.5
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0

dependency_overrides:
  meta: ^1.9.1


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
#  assets:
#    - assets/
#    - assets/icons/
#    - assets/images/
#    - assets/fonts/
#    - assets/svgs/
#    - assets/gif/
#
#
#  fonts:
#    - family: poppins
#      fonts:
#        - asset: assets/fonts/poppins/Poppins-Regular.ttf
#        - asset: assets/fonts/poppins/Poppins-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/poppins/Poppins-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/poppins/Poppins-Light.ttf
#          weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
